clear all;
close all;
b=1;
a=[1, 0.9];
x=randn(1064,1);
f=filter(b,a,x);
y=f(41:end);
subplot(3,1,1);
plot(x);
grid on;
title('Unfiltered WGN');
xlabel('Sample number');
ylabel('Magnitude');
subplot(3,1,2);
plot(y);
grid on;
title('Filtered WGN');
xlabel('Sample number');
ylabel('Magnitude');
figure;
zplane(b,a);
